# Introduction {#intro}

The article studies the link between transport disadvantage, social exclusion, and well-being. Within these categories in the study, the responses given further identified subcategories within transport disadvantage and social exclusion while well-being is identified within a ‘Satisfaction With Life Scale’. This research was conducted in 2008 in Melbourne, Australia using household surveys for a survey deliberately targeting both advantaged and disadvantaged households. Using the results of the survey links were made between transport disadvantage, social exclusion, and well-being using structural equation modelling. This model shows negative associations between social exclusion and well-being as well as between transport disadvantage and well-being, and a positive association between transport disadvantage and social exclusion. This article draws upon several other works that attempt to address the links between transport disadvantage and social exclusion as well as other works that draw links between transport and well-being. This research provides a new methodology of analyzing the data to be able to address all three points together. Because the research shows a negative correlation between transport disadvantage and well-being it can be inferred that when a person has less accessibility to transport, their personal sense of well-being diminishes. This is true as well for social exclusion. Along with this, because social exclusion and transport disadvantage were positively correlated, there is a link that if a person has a transport disadvantage, they are more likely to experience social exclusion. Thus, with the links between these three topics, it supports the idea that there is a link between transport disadvantage, accessibility, and mental health. 
