# Literature

There has been a large amount of research in recent years that discusses accessibility as well as mobility. However, there are many different ways to define both accessibility and mobility. For example, 
@currie2010modelling, (Schwanen et al., 2015), (Audirac, 2008), and (Delbosc & Currie, 2011) all define accessibility in some terms of being closely linked to transport disadvantage. They particularlyfocus on transport disadvantage caused by availability of resources, the design of the transport system, or physical, emotional, or mental disadvantages. Meanwhile, (Ermagun & Tilahun, 2020), and (Horner & Wood, n.d.) focus on the geographic distance of things as a measure of accessibility, and the actual physical capability ofreaching a location within a specific distance. Even more, (Delbosc et al., 2020) comments on accessibility and mobility as being measured by a behavior and trip making, while (Ciommo et al., 2014) looks not at a specific definition of accessibility or mobility, but on different variables that can affect the travel patterns of individuals. When looking at all these different definitions of mobility and ways to analyze data it is difficult to discern which, if any, is most correct. For this research we will be analyzing accessibility along the same lines of (Ermagun & Tilahun, 2020), using a gravity based model to track geographic distance to a certain location, along with time,using different modes of transportation. 

Along with accessibility, there are certain factors that can affect mobility, as discussed by the previously mentioned articles. One variable in particular that is mentioned by (Ciommo et al., 2014), (Schwanen et al., 2015), and (Delbosc & Currie, 2011)is social capital closely aligned with social exclusion. Social capital, or the amount of interaction an individual has and can draw upon in times of need is something that can help increase accessibility, by increasing access to transport resources. On the other side of that, social exclusion is closely correlated with transport disadvantage, and a much smaller accessibility. In addition to affecting accessibility, social exclusion also affects mental and emotional health, as well as perceived satisfaction with life. 

The analysis of well-being being connected with transport disadvantage is analyzed closely by (Currie & Delbosc, 2010). The model they used to analyze the data showed negative associations between social exclusion and well-being as well as between transport disadvantage and well-being, and a positive association between transport disadvantage and social exclusion. (Delbosc et al., 2020)models the causality between satisfaction with life and mobility. They are particularly concerned with discovering whether the relationship is bidirectional, and the research and analysis conducted did support this view. Both these studies show a strong correlation between perceived well-being and mobility. Previously discussedis the relationship between mobility and social capital. 

What we intend to discover in this research is the direct links between accessibility to certain resources and positive mental health. Although there have been research studies previously that haveshowed general trends that connect positive mental health with well-being, we are attempting to further isolate a specific accessibility model, and identify whether accessibilitytocertain locations, particularly parks, grocery stores, and libraries,have a higher 
correlation to increased mental health than others. We will use the ideas of social exclusion, transport disadvantage, accessibility, and well-being to analyze the data and determine a possible correlation. 
